#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

#Fibonacci function, returns Fib number at ith position
def fib(i):
    if i == 1:
        return 1
    if i == 2:
        return 2
    else:
        return fib(i - 1) + fib(i - 2)

x = 1
fibNum = 0
curNum = 0

while fibNum < 4000000:
    fibNum = fib(x)
    if fibNum % 2 == 0:
        curNum = curNum + fibNum
    x+=1

print(curNum)
